### PR TITLE
Bug 1794698: Last batch of changes to be backported to 4.3

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by stbenjam** [comment]
@elfosardo Thanks, looks like some merge conflicts though - how hard to address? Maybe the 4.3-ipv6 branch doesn't have everything openshift/ironic-image:4.3 does?

**Comment by elfosardo** [comment]
@stbenjam mmmm no, I checked, the branches don't have any difference apparently :/

**Comment by elfosardo** [comment]
@stbenjam nvm, I did a quick check only from commits point of view, but not from content where you can actaully see the differences.
We'll probably have to change some things manually

**Comment by elfosardo** [comment]
@stbenjam I'm closing this and using #2

**Pull request closed without merging**
